### ISSUE TITLE
.literal(string) input on a type with .literal() inside the type issue

### ISSUE THREAD

**Issue by gbvanrenswoude** [skunkteam/types#30]
When putting a .literal() inside a type, .literal(string) input is not accepted:

For example this is not accepted:

```
/** a secret bundle type */
export type SecretBundle = The<typeof SecretBundle>;
export const SecretBundle = object('SecretBundle', {
    api_key: NonEmptyString,
    password: NonEmptyString,
    user: NonEmptyString,
});

/** how we want to use the secret bundle */
export type SpecificMyappSecretBundle = The<typeof SpecificMyappSecretBundle>;
export const SpecificMyappSecretBundle = object('SpecificMyappSecretBundle', {
    MYAPP_API_USER: literal('MYTEAM'),
    MYAPP_API_PASSWORD: NonEmptyString,
    MYAPP_API_KEY: NonEmptyString,
});

const secrets = SecretBundle(JSON.parse(SecretString));
const parsedSecrets = SpecificMyappSecretBundle.literal({
    MYAPP_API_USER: secrets.user,
    MYAPP_API_PASSWORD: secrets.password,
    MYAPP_API_KEY: secrets.api_key,
});
```

And this is:

```
/** a secret bundle type */
export type SecretBundle = The<typeof SecretBundle>;
export const SecretBundle = object('SecretBundle', {
    api_key: NonEmptyString,
    password: NonEmptyString,
    user: NonEmptyString,
});

type MYTEAM = The<typeof MYTEAM>;
const MYTEAM = literal('MYTEAM');

/** how we want to use the secret bundle */
export type SpecificMyappSecretBundle = The<typeof SpecificMyappSecretBundle>;
export const SpecificMyappSecretBundle = object('SpecificMyappSecretBundle', {
    MYAPP_API_USER: MYTEAM,
    MYAPP_API_PASSWORD: NonEmptyString,
    MYAPP_API_KEY: NonEmptyString,
});

const secrets = SecretBundle(JSON.parse(SecretString));
const parsedSecrets = SpecificMyappSecretBundle.literal({
    MYAPP_API_USER: MYTEAM(secrets.user),
    MYAPP_API_PASSWORD: secrets.password,
    MYAPP_API_KEY: secrets.api_key,
});
```

**Comment by wvanderdeijl** [comment]
We should see if we can enhance `DeepUnbranded` so that literal string types like 'FOO' get widened to plain `string`. That would mean that `BaseTypeImpl.literal` would accept a plain string.

**Comment by wvanderdeijl** [comment]
After some investigation, we feel that broadening literal types to their base type in `DeepUnbranded` is not a good idea. Although it adds some convenience in the reported scenario, it is not that complicated to run the string though it's type, as with `MYTEAM(secrets.user)` in the example.

Broadening these to string would loose the ability to use a string literal as discriminator in a union type. See the following example:
```typescript
type Outcome = The<typeof Outcome>;
const Outcome = union([
    object({ status: literal('ok') }),
    object({ status: literal('error'), message: string }),
]);
```

This uses the `status` field as discriminator between the two union types. The `DeepUnbranded` typescript type is:
```typescript
{ status:'ok' } | { status:'error', message:string }
```

If we would broaden the `ok` and `error` type to string this would be:
```
{ status:string } | { status:string, message:string }
```
 and you would loose the knowledge that message is mandatory when the status is 'error', meaning this would no longer throw a typescript error:
```typescript
Outcome.literal({ status: 'error' });
```

It would also no longer throw a TS compile error on:
```typescript
Outcome.literal({ status: 'wrong' });
```

We feel loosing the string literal types would be greater loss than the convenience of not having to run a string through it's type-checker.
